version: '3'

services:
  db:
    build:
      context: ./build/db
      dockerfile: Dockerfile
    ports:
      - 1433:1433
    volumes:
      - ../database:/var/opt/mssql/database
    enviroment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SA_PASSWORD}
    command: sh -c "./initialize.sh -d ${SQL_DB_NAME} -p ${SQL_SA_PASSWORD} & /opt/mssql/bin/sqlservr"

  api:
    build: 
      context: ./build/api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString:Default=server=db; database=${SQL_DB_NAME};user id='sa';password='${SQL_SA_PASSWORD}'; Integrated Security=false; Encrypt=True;TrustServerCertificate=True
      - DOTNET_USE_POLLING_FILE_WATCHER 1
    valumes:
      - ../src/${API_NAME}:/app
    ports:
      - 5000:5000
    depends_on:
      - db

  app:
    build:
      context: ./build/app
      dockerfile: Dockerfile
      args:
        APP_NAME: ${APP_NAME}
    volumes:
      - ../src/${APP_NAME}:/app/${APP_NAME}
    environment:
      - WATCHPACK_POLLING=true
      - APP_NAME=${APP_NAME}
    ports:
      - 3000:3000
    depends_on:
      - db
      - api
    command: sh -c "yarn install && yarn dev"